"""
Celery tasks for building generated Spring Boot projects.

Extracts generated files to a temporary directory, runs Maven, and streams
build output line-by-line to Redis pub/sub so WebSocket clients can display
a live build log.
"""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, Optional

import structlog
from celery import Task
from celery.exceptions import SoftTimeLimitExceeded
from sqlalchemy import select

from api.tasks.celery_app import celery_app

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
#  Helpers — async bridge (same pattern as migration_tasks)
# ---------------------------------------------------------------------------


def _run_async(coro):
    """Run an async coroutine from synchronous Celery task context."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor() as pool:
                future = pool.submit(asyncio.run, coro)
                return future.result()
        else:
            return loop.run_until_complete(coro)
    except RuntimeError:
        return asyncio.run(coro)


async def _get_session():
    """Create a standalone async session for use inside Celery workers."""
    from api.database import _get_session_factory
    factory = _get_session_factory()
    return factory()


async def _get_redis():
    """Create a standalone Redis connection for Celery workers."""
    import redis.asyncio as aioredis
    from api.config import get_settings
    settings = get_settings()
    return aioredis.from_url(settings.redis.url, decode_responses=True)


async def _publish_build_event(build_id: str, event: Dict[str, Any]) -> None:
    """Publish a build event to the Redis channel."""
    redis = await _get_redis()
    try:
        channel = f"build:{build_id}:output"
        await redis.publish(channel, json.dumps(event))

        # Store for replay
        event_key = f"build:{build_id}:event_log"
        score = event.get("timestamp", time.time())
        await redis.zadd(event_key, {json.dumps(event): score})
        await redis.zremrangebyrank(event_key, 0, -1001)
        await redis.expire(event_key, 86400)
    finally:
        await redis.close()


# ---------------------------------------------------------------------------
#  POM generation
# ---------------------------------------------------------------------------

_DEFAULT_POM_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>{group_id}</groupId>
    <artifactId>{artifact_id}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{project_name}</name>
    <description>Auto-generated Spring Boot project from MuleSoft migration</description>

    <properties>
        <java.version>{java_version}</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""


def _generate_pom(
    project_dir: Path,
    group_id: str = "com.example",
    artifact_id: str = "migrated-app",
    project_name: str = "Migrated Application",
    java_version: str = "17",
) -> None:
    """Write a fallback pom.xml if one wasn't generated by the agents."""
    pom_path = project_dir / "pom.xml"
    if not pom_path.exists():
        content = _DEFAULT_POM_TEMPLATE.format(
            group_id=group_id,
            artifact_id=artifact_id,
            project_name=project_name,
            java_version=java_version,
        )
        pom_path.write_text(content, encoding="utf-8")
        logger.info("build.pom_generated", path=str(pom_path))


# ---------------------------------------------------------------------------
#  File extraction
# ---------------------------------------------------------------------------


def _extract_files(output_files: Dict[str, str], target_dir: Path) -> int:
    """
    Write generated source files into the target directory.

    Args:
        output_files: Mapping of relative filepath -> file content.
        target_dir: Root directory to write files into.

    Returns:
        Number of files written.
    """
    count = 0
    for rel_path, content in output_files.items():
        # Sanitize path to prevent directory traversal
        safe_path = Path(rel_path).parts
        if ".." in safe_path:
            logger.warning("build.skipped_unsafe_path", path=rel_path)
            continue

        full_path = target_dir / Path(*safe_path)
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        count += 1

    return count


# ---------------------------------------------------------------------------
#  Maven build execution
# ---------------------------------------------------------------------------


def _run_maven_build(
    project_dir: Path,
    build_id: str,
) -> tuple[int, str]:
    """
    Run ``mvn clean package -DskipTests`` and stream output to Redis.

    Returns:
        A tuple of (exit_code, full_build_log).
    """
    maven_cmd = shutil.which("mvn") or "mvn"
    cmd = [
        maven_cmd,
        "clean",
        "package",
        "-DskipTests",
        "-Dmaven.test.skip=true",
        "-Dmaven.compiler.failOnError=false",
        "-B",  # batch mode (no interactive input)
        "--no-transfer-progress",
    ]

    log_lines: list[str] = []
    line_number = 0

    try:
        process = subprocess.Popen(
            cmd,
            cwd=str(project_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env={**os.environ, "JAVA_HOME": os.getenv("JAVA_HOME", "")},
        )

        for line in iter(process.stdout.readline, ""):
            line = line.rstrip("\n")
            log_lines.append(line)
            line_number += 1

            # Stream each line to Redis pub/sub
            _run_async(_publish_build_event(build_id, {
                "type": "build_output",
                "build_id": build_id,
                "line": line,
                "line_number": line_number,
                "timestamp": time.time(),
            }))

        process.wait()
        exit_code = process.returncode

    except FileNotFoundError:
        error_msg = "Maven (mvn) not found on PATH. Please install Maven."
        log_lines.append(error_msg)
        _run_async(_publish_build_event(build_id, {
            "type": "build_output",
            "build_id": build_id,
            "line": error_msg,
            "line_number": line_number + 1,
            "is_error": True,
            "timestamp": time.time(),
        }))
        exit_code = 127

    except Exception as exc:
        error_msg = f"Build process error: {exc}"
        log_lines.append(error_msg)
        exit_code = 1

    full_log = "\n".join(log_lines)
    return exit_code, full_log


# ---------------------------------------------------------------------------
#  Task: run_build
# ---------------------------------------------------------------------------


class BuildTask(Task):
    """Custom base task with retry for transient failures."""

    autoretry_for = (ConnectionError, OSError)
    retry_backoff = True
    retry_backoff_max = 60
    retry_jitter = True
    max_retries = 2


@celery_app.task(
    bind=True,
    base=BuildTask,
    name="api.tasks.build_tasks.run_build",
    acks_late=True,
    reject_on_worker_lost=True,
    track_started=True,
)
def run_build(
    self,
    build_id: str,
    migration_id: str,
) -> Dict[str, Any]:
    """
    Build generated Spring Boot code with Maven.

    Extracts files from the MigrationJob's output, generates a pom.xml if
    missing, runs Maven, and records the result in the BuildJob row.

    Args:
        build_id: UUID of the BuildJob row.
        migration_id: UUID of the parent MigrationJob.

    Returns:
        A dict with build status, exit code, and duration.
    """
    logger.info(
        "build.task_started",
        build_id=build_id,
        migration_id=migration_id,
        task_id=self.request.id,
    )

    tmp_dir = None
    try:
        result = _run_async(_execute_build(self, build_id, migration_id))
        return result
    except SoftTimeLimitExceeded:
        logger.error("build.soft_timeout", build_id=build_id)
        _run_async(_mark_build_finished(build_id, exit_code=124, log="Build timed out"))
        _run_async(_publish_build_event(build_id, {
            "type": "build_failed",
            "build_id": build_id,
            "reason": "timeout",
            "timestamp": time.time(),
        }))
        return {"status": "timed_out", "build_id": build_id}
    except Exception as exc:
        logger.error(
            "build.task_error",
            build_id=build_id,
            error=str(exc),
            exc_info=True,
        )
        _run_async(_mark_build_finished(build_id, exit_code=1, log=str(exc)))
        _run_async(_publish_build_event(build_id, {
            "type": "build_failed",
            "build_id": build_id,
            "error": str(exc),
            "timestamp": time.time(),
        }))
        raise self.retry(exc=exc)


async def _execute_build(
    task: Task,
    build_id: str,
    migration_id: str,
) -> Dict[str, Any]:
    """Core async logic for a build run."""
    from api.models.build import BuildJob
    from api.models.migration import MigrationJob

    # ── Load MigrationJob to get output files ──────────────────
    session = await _get_session()
    try:
        mig_result = await session.execute(
            select(MigrationJob).where(MigrationJob.id == migration_id)
        )
        migration = mig_result.scalar_one_or_none()
        if migration is None:
            raise ValueError(f"MigrationJob {migration_id} not found")

        output_files: Dict[str, str] = migration.output_files or {}
        if not output_files:
            raise ValueError(f"MigrationJob {migration_id} has no output files to build")

        project_name = migration.project_name
        group_id = migration.group_id
        java_version = migration.java_version

        # Mark build as running
        build_result = await session.execute(
            select(BuildJob).where(BuildJob.id == build_id)
        )
        build_job = build_result.scalar_one_or_none()
        if build_job is None:
            raise ValueError(f"BuildJob {build_id} not found")

        build_job.mark_running()
        await session.commit()
    except Exception:
        await session.rollback()
        raise
    finally:
        await session.close()

    # ── Publish build_started event ────────────────────────────
    await _publish_build_event(build_id, {
        "type": "build_started",
        "build_id": build_id,
        "migration_id": migration_id,
        "project_name": project_name,
        "file_count": len(output_files),
        "timestamp": time.time(),
    })

    # ── Extract files to temp directory ────────────────────────
    tmp_dir = Path(tempfile.mkdtemp(prefix=f"build_{build_id[:8]}_"))
    try:
        file_count = _extract_files(output_files, tmp_dir)
        logger.info(
            "build.files_extracted",
            build_id=build_id,
            count=file_count,
            dir=str(tmp_dir),
        )

        # Generate pom.xml if not present
        artifact_id = project_name.lower().replace(" ", "-")
        _generate_pom(
            tmp_dir,
            group_id=group_id,
            artifact_id=artifact_id,
            project_name=project_name,
            java_version=java_version,
        )

        # ── Run Maven build ────────────────────────────────────
        start_time = time.monotonic()
        exit_code, full_log = _run_maven_build(tmp_dir, build_id)
        duration_ms = int((time.monotonic() - start_time) * 1000)

        # ── Update BuildJob in DB ──────────────────────────────
        await _mark_build_finished(
            build_id,
            exit_code=exit_code,
            log=full_log,
        )

        # ── Publish completion event ───────────────────────────
        status = "completed" if exit_code == 0 else "failed"
        await _publish_build_event(build_id, {
            "type": "build_complete" if exit_code == 0 else "build_failed",
            "build_id": build_id,
            "migration_id": migration_id,
            "exit_code": exit_code,
            "status": status,
            "duration_ms": duration_ms,
            "timestamp": time.time(),
        })

        logger.info(
            "build.task_completed",
            build_id=build_id,
            exit_code=exit_code,
            duration_ms=duration_ms,
        )

        return {
            "status": status,
            "build_id": build_id,
            "migration_id": migration_id,
            "exit_code": exit_code,
            "duration_ms": duration_ms,
        }
    finally:
        # ── Clean up temp directory ────────────────────────────
        try:
            shutil.rmtree(tmp_dir, ignore_errors=True)
            logger.debug("build.tmp_cleaned", dir=str(tmp_dir))
        except Exception as exc:
            logger.warning(
                "build.tmp_cleanup_failed",
                dir=str(tmp_dir),
                error=str(exc),
            )


# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------


async def _mark_build_finished(
    build_id: str,
    exit_code: int,
    log: str = "",
) -> None:
    """Update the BuildJob row with final results."""
    from api.models.build import BuildJob

    session = await _get_session()
    try:
        result = await session.execute(
            select(BuildJob).where(BuildJob.id == build_id)
        )
        job = result.scalar_one_or_none()
        if job:
            job.build_log = log[-50_000:]  # truncate to 50 KB
            job.mark_completed(exit_code)
            await session.commit()
    except Exception:
        await session.rollback()
    finally:
        await session.close()
